language: php

php:
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.2

script:
  - make
  - make test
  - make build-distr
  - travis setup releases

deploy:
  provider: releases
  file: ./build/jbzoo_installer.zip
  skip_cleanup: true
  on:
    tags: true
