language: php

php:
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.2

script:
  - make
  - make test
  - make build-distr

deploy:
  provider: releases
  file: ./build/jbzoo_installer.zip
  skip_cleanup: true
  api_key: "09f5a70579e3614c04db6f366de67ed81bf2db61"
  on:
    tags: true
