name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, zip

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install dependencies (dev)
      run: composer install --optimize-autoloader --no-interaction --no-progress

    - name: Build installer
      run: |
        mkdir -p ./build/files
        cp -R ./src/packages ./build/files/packages
        cp ./src/file.script.php ./build/files/file.script.php
        cp ./src/pkg_jbzoo.xml ./build/files/pkg_jbzoo.xml
        cp ./README.md ./build/files/README.md
        cp ./LICENSE.md ./build/files/LICENSE.md
        cd ./build/files
        zip -r9q jbzoo_clean_install.zip *
        mv ./build/files/jbzoo_clean_install.zip ./build/jbzoo_clean_install.zip
        rm -rf ./build/files

    - name: Build update package
      run: |
        mkdir -p ./build/files
        cp -R ./src/packages ./build/files/packages
        cp ./src/file.script.php ./build/files/file.script.php
        cp ./src/pkg_jbzoo.xml ./build/files/pkg_jbzoo.xml
        cp ./README.md ./build/files/README.md
        cp ./LICENSE.md ./build/files/LICENSE.md
        find ./build/files -name 'positions.config' -delete
        find ./build/files -name 'positions.xml' -delete
        find ./build/files -name 'metadata.xml' -delete
        rm -rf ./build/files/packages/jbuniversal/jbuniversal/templates
        cd ./build/files
        zip -r9q jbzoo_update.zip *
        mv ./build/files/jbzoo_update.zip ./build/jbzoo_update.zip
        rm -rf ./build/files

    - name: Cleanup project
      run: rm -rf ./vendor/
